name: Deploy to gitHub Pages
on:
  pull_request:
    types: closed
    branches: 
      - main
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.1.1
      - name: Install dependencies
        run: bun install
      - name: Generate folder structure
        run: bun foldergen
      - name: Build react app
        run: bun run build # 'run' is required to differentiate the script from the command
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:      
          path: ./dist
          name: github-pages
  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.4
        
